name: Deploy to S3

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v4

     # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    # 3. Instalar Ionic
    - name: Install Ionic
      run: npm install -g @ionic/cli

    # 4. Instalar dependencias del frontend
    - name: Install dependencies
      run: npm install

    # 5. Compilar el proyecto
    - name: Build Ionic frontend (Release)
      run: ionic build --prod --configuration=web

    # 6. Configurar AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 7. Sync files
    - name: Copying web files to AWS
      run: |
        aws s3 sync ./www/ s3://comunika-web --exact-timestamps